export default [
  {
    id: 1,
    name: "Pasqua Emeka",
    course: "Know Your Color",
    data: "24/5/2022",
    status: "Approved",
  },
  {
    id: 2,
    name: "Dominic Nweke",
    course: "Know Your Color",
    data: "24/5/2022",
    status: "pending",
  },
  {
    id: 3,
    name: "Bell Omuboye",
    course: "Know Your Color",
    data: "24/5/2022",
    status: "Approved",
  },
  {
    id: 4,
    name: "Chidera Nweze",
    course: "Know Your Color",
    data: "24/5/2022",
    status: "pending",
  },
  {
    id: 5,
    name: "Nenye Nwangwu",
    course: "Know Your Color",
    data: "24/5/2022",
    status: "pending",
  },
  {
    id: 6,
    name: "Endee Onyeukwu",
    course: "Know Your Color",
    data: "24/5/2022",
    status: "pending",
  },
  {
    id: 7,
    name: "Endee Onyeukwu",
    course: "Know Your Color",
    data: "24/5/2022",
    status: "pending",
  },
  {
    id: 8,
    name: "Endee Onyeukwu",
    course: "Know Your Color",
    data: "24/5/2022",
    status: "pending",
  },
  {
    id: 9,
    name: "Endee Onyeukwu",
    course: "Know Your Color",
    data: "24/5/2022",
    status: "pending",
  },
];
